### ISSUE TITLE
v0.6.1: Server failed to load datapack (incompatibilities)

### ISSUE THREAD

**Issue by No3371** [fzzyhmstrs/EMI_loot#16]
```
[01:48:33] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.util.NoSuchElementException: No value present
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:194) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.14.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.14.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.14.jar:?]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:143) ~[?:?]
        at twilightforest.item.PhantomArmorItem.canApplyAtEnchantingTable(PhantomArmorItem.java:58) ~[twilightforest-fabric-1.19.2-4.2.335.jar:?]
        at net.minecraft.class_1887.handler$zbk000$port_lib$canEnchant(class_1887.java:532) ~[server-intermediary.jar:?]
        at net.minecraft.class_1887.method_8192(class_1887.java) ~[server-intermediary.jar:?]
        at com.cursery.enchant.CurseEnchantmentHelper.rollAndApplyCurseTo(CurseEnchantmentHelper.java:166) ~[cursery-fabric-1.19.2-3.1.jar:?]
        at com.cursery.enchant.CurseEnchantmentHelper.checkForRandomCurse(CurseEnchantmentHelper.java:98) ~[cursery-fabric-1.19.2-3.1.jar:?]
        at net.minecraft.class_1799.handler$cmm000$afterEnchant(class_1799.java:6671) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.method_7978(class_1799.java:899) ~[server-intermediary.jar:?]
        at fzzyhmstrs.emi_loot.parser.function.EnchantWithLevelsFunctionParser.parseFunction(EnchantWithLevelsFunctionParser.java:23) ~[emi_loot-0.6.1+1.19.jar:?]
        at fzzyhmstrs.emi_loot.parser.registry.LootParserRegistry.parseFunction(LootParserRegistry.java:50) ~[emi_loot-0.6.1+1.19.jar:?]
        at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootFunction(LootTableParser.java:485) ~[emi_loot-0.6.1+1.19.jar:?]
        at fzzyhmstrs.emi_loot.parser.LootTableParser.applyLootFunctionToItem(LootTableParser.java:507) ~[emi_loot-0.6.1+1.19.jar:?]
        at fzzyhmstrs.emi_loot.parser.LootTableParser.parseItemEntry(LootTableParser.java:352) ~[emi_loot-0.6.1+1.19.jar:?]
        at fzzyhmstrs.emi_loot.parser.LootTableParser.parseItemEntry(LootTableParser.java:348) ~[emi_loot-0.6.1+1.19.jar:?]
        at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootPoolEntry(LootTableParser.java:328) ~[emi_loot-0.6.1+1.19.jar:?]
        at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootPoolEntry(LootTableParser.java:321) ~[emi_loot-0.6.1+1.19.jar:?]
        at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootPoolEntry(LootTableParser.java:309) ~[emi_loot-0.6.1+1.19.jar:?]
        at fzzyhmstrs.emi_loot.parser.LootTableParser.parseChestLootTable(LootTableParser.java:191) ~[emi_loot-0.6.1+1.19.jar:?]
        at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootTable(LootTableParser.java:123) ~[emi_loot-0.6.1+1.19.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
        at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootTables(LootTableParser.java:97) ~[emi_loot-0.6.1+1.19.jar:?]
        at net.minecraft.class_60.handler$ddn000$emi_loot_lootTablesAfterFabric(class_60.java:5540) ~[server-intermediary.jar:?]
        at net.minecraft.class_60.method_20712(class_60.java:59) ~[server-intermediary.jar:?]
        at net.minecraft.class_60.method_18788(class_60.java:17) ~[server-intermediary.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43498(class_156.java:958) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43499(class_156.java:946) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:156) ~[server-intermediary.jar:?]
        ... 4 more
```

**Comment by fzzyhmstrs** [comment]
This may be fixed in 0.6.2. This seems to have something to do with enchanting, and I tweaked how the Random Enchantment is applied.
